alexa-games/litexa

docs/book/backdoor.md, docs/reference/README.md, packages/litexa/src/parser/intent.coffee, packages/litexa/src/parser/litexa.pegjs, packages/litexa/src/parser/skill.coffee, packages/litexa/src/parser/state.coffee, tests/data/intents/litexa/main.litexa, tests/data/localization/litexa/main.litexa, tests/data/sound/litexa/main.litexa, tests/data/sound/litexa/main.test.litexa, tests/features/intents.spec.coffee, tests/features/localization.spec.coffee, tests/features/sound.spec.coffee
New syntax shorthand that allows assigning multiple intents to the same handler.
* Now allows alternatives in `when` handlers to specify intent names as an option. These cannot be intermixed with utterance alternatives.
* Gives a warning that intents which are defined without utterances are not added to the language model (unfortunately this is run twice in `litexa test`)
* Also changes some variables to constants in pegjs.
This feature reduces the need for either an extra state or duplicate code when you may want 2 intents to have the same behavior.
Addresses issue #89.
* npm run release
* test skill - litexa model, litexa deploy, litexa test. Verified that the generated handler code is as expected.
[license]: …
=> feat: multi-intent handlers

docs/book/testing.md, packages/litexa/src/command-line/router.coffee, packages/litexa/src/command-line/test.coffee, packages/litexa/src/parser/skill.coffee, packages/litexa/src/parser/testing.coffee, tests/preamble.coffee
Added an optional raw data dump command for the test CLI.
If used, this command will enabling dumping of all requests, responses, and DB contents into `.test/output.json`.
This PR also includes changes that enable the output of the names of tests that failed.
To give developers the ability to optionally toggle potentially large and detailed log data during testing.
=> feat: added optional raw data dump command to test CLI

docs/book/state-management.md
Sample didn't compile before, was just missing the variable declaration and assignment for the result of the map operation.
=> docs: add missing variable to sample for slot builders

packages/litexa-html/README.md, packages/litexa/src/command-line/deploy/manifest.coffee
If a skill is utilizing an extension that requires an Alexa interface enablement, Litexa will auto-enable said interface on deployment.
To simplify the skill deployment process even further when using Litexa extensions.
Ran unit and integration tests.
- [] Bug fix (non-breaking change which fixes an issue)
=> feat: made it so that extension interfaces are auto-enabled

packages/litexa/src/parser/state.coffee
The warning `'HelloIntent' does not have utterances; not adding to language model.` is a false positive for events (events are not added to language models).
Also, `litexa test` seems to run this twice - once to build the model, once in the test execution? Added a check for testDevice which is set during testing to remove the duplication.
As of the multi-intent handler change, Litexa will warn in any step when building the model about intents it detects that doesn't have any utterances (besides built-in), that it will not add those intents to the model. It has been detecting events (e.g 'Connections.Response') as such intents, to which the warning doesn't apply because events are not part of the language model.
Events are (as far as we know) guaranteed to have a period in their name, so …
=> fix: remove inapplicable warning for not adding events to language model

packages/litexa/src/command-line/templates/common/typescript/config/globals.d.ts
Forgot to do this as a part of #106 .
Update the typescript litexa config definition.
If a user is using typescript, a `npm run compile` will error out on litexa config if it uses this field.
`litexa generate` with typescript configuration
=> fix: update globals.d.ts for dynamoDbConfiguration

packages/litexa/src/command-line/templates/bundled/coffee/package.json, packages/litexa/src/command-line/templates/bundled/javascript/package.json, packages/litexa/src/command-line/templates/bundled/typescript/source/package.json, packages/litexa/src/command-line/templates/common/typescript/config/package.json, packages/litexa/src/command-line/templates/inlined/typescript/package.json, packages/litexa/src/command-line/templates/separate/coffee/package.json, packages/litexa/src/command-line/templates/separate/javascript/package.json, packages/litexa/src/command-line/templates/separate/typescript/package.json
Updated the dependencies that the Litexa project templates use.
To keep the project templates, which are a great entry point and learning experience for Litexa developers, as up-to-date as possible.
Full integration tests. 
Generated multiple Litexa projects - one for each template - and ran:
* `litexa deploy`, 
* `litexa test`, 
* and other pre-created NPM scripts like:
* `npm run compile`,
* `npm run test`,
* `npm run lint`. 
Then tested each of the deployed skills.
=> fix: update litexa template dependencies

docs/book/screens.md
Fix a path within the documentation. Litexas functionality is not affected by this change.
=> fix: Fix path to property named 'title' in APL documentation

packages/litexa/src/command-line/localization.js, packages/litexa/src/parser/say.coffee
The absolute file references appear to be causing issues when locally installing the @litexa/core package on Node 10, from scratch. Switching them to local references, to be safe.
=> fix: Switched a couple absolute to relative file references.

README.md
Made it more clear that Litexa officially supports Node.js v10.x.
=> docs: note that node 10.x is supported version

packages/litexa/src/command-line/templates/inlined/typescript/package.json
Update inlined TypeScript template's NPM test script names to be more accurate / match its README.md.
=> chore: update inlined typescript npm test scripts to be more accurate

README.md, docs/book/appendix-default-aws-settings.md
Where we explain Lambda runtime environments and its default settings, add link to lambda config section of deployment chapter.
=> docs: add more links to lambda config section

.github/workflows/windows.yml, .travis.yml, package.json
Added Node.js 12 to CI build matrices. But since the  `lame` package is not compatible in most Node.js 12 environments, we now ignore `@litexa/assets-wav` extension in our build stages in our Node.js 12 CI virtual environments.
Side notes:
* The GitHub Actions `windows-2016` environment is being removed (scheduled for January 2020), so I updated our GitHub Actions to use `windows-2019`. More here https://help.github.com/en/actions/automating-your-workflow-with-github-actions/virtual-environments-for-github-hosted-runners#supported-runners-and-hardware-resources
=> ci: add node 12 to build matrix

.github/workflows/windows.yml, .travis.yml, package.json
Reverting #127. More complexity than first thought when upgrading CI/CD workflows to use Node 12. More information is being tracked in issue #134.
=> chore: reverting "ci: add node 12 to build matrix"

docs/book/backdoor.md, packages/litexa-html/README.md
Fleshing out the HTML extension's README. Making it more clear:
* Add information about the Alexa Web API interface + skill manifest
* Add usage details around the extension's use of the APIs directives & event
* Start to add more details to the `mark` tag section
=> docs: flesh out HTML extension's README

docs/book/backdoor.md, docs/book/expressions.md
Added responsePostProcessor documentation to the section on modifying responses.
Organized backdoor.md by cognitive load, with the heavier context object info last. 
Moved the DBKey override information next to the conversation about database storage in the variables pages instead.
=> docs: added responsePostProcessor, reorganized backdoor for narrative flow

.travis.yml, packages/litexa-deploy-aws/src/lambda.coffee
Bumping up the travis coverage to all node versions that should be currently supported.
=> chore: add nodejs versions 12 and 14 to the travis test suite

packages/litexa-deploy-aws/src/utils/s3Utils.coffee, packages/litexa-deploy-aws/test/utils/s3Utils.spec.coffee
Fixes #153.
Windows subdirectories use the "\\" character, which is not valid in S3 asset paths during the step where Litexa searches for all assets that need to be uploaded.
#153 
npm run test in litexa deploy package
=> fix: fix asset subdirectory path on upload (#153)

packages/litexa/src/command-line/api/smapi.coffee
This adds minor logic to ignore messages about asynchronous processes in ask-cli SMAPI mode, rather than treat them as an error.
This was preventing deployments if the user had upgraded to ask-cli v2.11 or newer. 
Tested deploying a new default skill, then updating it from a Mac, with node v10.21.0 & v12.13.1 and ask-cli v2.11.2 & v1.7.23
=> fix: ignore ASK cli [Warn] async messages during deploy

packages/litexa/src/parser/litexa.pegjs, tests/data/say-formatting/litexa/main.litexa
Quick fix for an oldie closing #116 allowing the syntax say "that \"thing\" you said"
Note, while this doesn't appear to do anything in most SSML renderers, it is valid syntax so we'll support it.
Tested on OSX, with node v10.21.0, ran the test suite.
=> fix: adding support for escaped quote characters in say strings

package-lock.json, packages/litexa/package-lock.json, packages/litexa/package.json, packages/litexa/src/command-line/project-info.coffee
Turns out that the path returned from the globalModulesPath isn't correct specifically when in Window and using nvm to manage node versions. The replacement globalDirectories module gets it right.
Without this patch, Windows users who also use nvm could not use globally installed Litexa extensions at all.
Tested on Windows, with node v10.22.0. Ran the standard test suite, and experimented with installing global extensions and verifying they were found with `litexa extensions`.
=> fix: globally installed extensions now work on Windows + nvm

packages/litexa/src/parser/handler.coffee, packages/litexa/test/specs/parser/handler.spec.coffee
Injects extensions before the parser needs to use them
Injects extensions before parser tries to use them
Currently only injects extensions if the first request is a standard supported use case. This prevents extensions from working on custom intent types.
https://github.com/alexa-games/litexa/issues/201
Added a new unit test and verified in a live litexa skill
=> fix: request parser always injects extensions
